# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

filebeat.inputs:
  # - type: container
  #   enabled: true
  #   paths: -/var/lib/docker/containers/*/*.log
  #   stream: all # can be all, stdout or stderr
  - type: filestream
    id: my-filestream-id
    paths:
      - /var/log/*.log*
      - /var/log/dmesg*
    prospector.scanner.exclude_files: ['\.gz$']
#========================== Filebeat autodiscover ==============================
# See this URL on how to run Apache2 Filebeat module: # https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
filebeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
      # This URL alos contains instructions on multi-line logs
      hints.enabled: true
#================================ Processors ===================================
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale:
      format: offset
  - add_host_metadata:
      netinfo.enabled: true
#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]
  pipeline: filebeat_pipeline
#============================== Dashboards =====================================
setup.dashboards:
  enabled: true
#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}:5601"
#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch:
path.data: /var/lib/beats
