server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/hapi-fhir?currentSchema=hapi-fhir&user=postgres&password=admin"
    username: "postgres"
    password: "amdin"
    driver.class-name: org.postgresql.Driver
    # max-active: 15
    # hikari:
    #   connectionTimeout: 20000
    #   maximumPoolSize: 5
  jpa:
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
# logging:
#   level:
#     org.springframework: INFO
#     com.mkyong: DEBUG
#   pattern:
#     console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#     file: "%d %p %c{1.} [%t] %m%n"
#   file: app.log
