# Use postgres/example user/password credentials
version: "3.1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      xpack.security.enabled: false
      http.host: 0.0.0.0
      # network.host: 0.0.0.0
      node.name: es01
      cluster.name: elasticsearch
    volumes:
      - esdata-test-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
    restart: always
    networks:
      - elastic-net
  fluentd:
    build: ./efk/fluentd
    # image: fluent/fluentd:edge-debian
    container_name: fluentd
    volumes:
      - ./efk/fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
      - /var/log/:/fluentd/log/auth/
      - ./efk/fluentd/logs:/fluentd/log/logs/
      - ./efk/fluentd/templates/:/fluentd/templates/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    links: # Sends incoming logs to the elasticsearch container.
      - elasticsearch
    networks:
      - elastic-net
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ES_JAVA_OPTS: -Xmx512m -Xms512m
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links: # Links kibana service to the elasticsearch container
      - elasticsearch
    # volumes:
    #   - ./efk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    networks:
      - elastic-net
volumes:
  esdata-test-1:
    driver: local
networks:
  elastic-net:
    name: elastic-net
